favicon: null
name: mutts
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3510638
  brandStrength: 0.25
  rhythmicContrast: 0.5
  brandColors:
    - '#C8C4BB'
    - '#E4E3E1'
    - '#2B292A'
    - '#925945'
    - '#6B3C32'
  lightness: 0.625
typography_spectrum: 0.06382979
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9914894
analytics:
  twitter: null
  google: null
  facebook: null
